import React, { useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Heart, MessageCircle, Send, User, LogOut, Image as ImageIcon, Video, ShieldCheck, MessageSquare, Home, Wallet, Paperclip, X, CheckCircle2 } from 'lucide-react'
import { supabase } from './lib/supabase'
import { moderateText } from './lib/moderation'
import './index.css'

type Profile = { id: string; username: string | null; full_name: string | null; avatar_url: string | null; bio?: string | null; is_vip?: boolean; vip_expires_at?: string | null }
type Post = { id: string; author_id: string; content: string | null; media_url: string | null; media_type: string | null; created_at: string; profiles?: Profile; likes?: { user_id: string }[] }
type Comment = { id: string; post_id: string; author_id: string; content: string; created_at: string; profiles?: Profile }
type ChatMessage = { id: string; sender_id: string; recipient_id: string; content: string; created_at: string }

const PAGE_SIZE = 12
const MAX_IMAGE = 8 * 1024 * 1024
const MAX_VIDEO = 30 * 1024 * 1024

function Auth({ onLegal }: { onLegal: (page: 'terms' | 'privacy') => void }) {
  const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [sent, setSent] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  if (!supabase) return <div className="max-w-md mx-auto mt-16 p-6 rounded-3xl bg-slate-900 border border-slate-800"><h1 className="text-3xl font-black">D Social</h1><p className="mt-3 text-slate-400">Cấu hình VITE_SUPABASE_URL và VITE_SUPABASE_PUBLISHABLE_KEY để bật backend.</p></div>
  const google = async () => { const { error } = await supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: window.location.origin } }); if (error) setError(error.message) }
  const emailLogin = async () => { setError(''); if (!email || password.length < 6) return setError('Email hợp lệ và mật khẩu tối thiểu 6 ký tự.'); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) { const sign = await supabase.auth.signUp({ email, password }); if (sign.error) setError(sign.error.message) } }
  const sendOtp = async () => { const { error } = await supabase.auth.signInWithOtp({ phone }); if (error) setError(error.message); else setSent(true) }
  const verifyOtp = async () => { const { error } = await supabase.auth.verifyOtp({ phone, token: otp, type: 'sms' }); if (error) setError(error.message) }
  return <div className="min-h-screen flex items-center justify-center p-4"><div className="w-full max-w-md p-6 rounded-3xl bg-slate-900 border border-slate-800 shadow-2xl"><div className="w-14 h-14 rounded-2xl bg-white text-slate-950 grid place-items-center text-3xl font-black">D</div><h1 className="text-3xl font-black mt-5">D Social</h1><p className="text-slate-400 mt-1">Kết nối đơn giản. Realtime. An toàn.</p><button onClick={google} className="w-full mt-6 py-3 rounded-xl bg-white text-slate-950 font-bold">Tiếp tục với Google</button><div className="my-5 border-t border-slate-800"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="w-full p-3 mb-2 rounded-xl bg-slate-800 outline-none"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu" type="password" className="w-full p-3 rounded-xl bg-slate-800 outline-none"/><button onClick={emailLogin} className="w-full mt-3 py-3 rounded-xl bg-indigo-500 font-bold">Đăng nhập / đăng ký</button><div className="my-5 border-t border-slate-800"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Số điện thoại +84..." className="w-full p-3 rounded-xl bg-slate-800 outline-none"/>{!sent ? <button onClick={sendOtp} className="w-full mt-2 py-3 rounded-xl bg-slate-700 font-bold">Gửi OTP</button> : <><input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="Mã OTP" className="w-full p-3 mt-2 rounded-xl bg-slate-800 outline-none"/><button onClick={verifyOtp} className="w-full mt-2 py-3 rounded-xl bg-emerald-500 font-bold">Xác nhận OTP</button></>}{error && <p className="text-red-400 mt-3 text-sm">{error}</p>}<div className="flex gap-3 mt-5 text-xs text-slate-500"><button onClick={()=>onLegal('terms')}>Điều khoản</button><button onClick={()=>onLegal('privacy')}>Chính sách bảo mật</button></div></div></div>
}

function Legal({ kind, onBack }: { kind: 'terms'|'privacy'; onBack:()=>void }) {
  return <main className="max-w-2xl mx-auto p-4 pb-20"><button onClick={onBack} className="mb-5 text-indigo-400">← Quay lại</button><article className="p-6 rounded-2xl bg-slate-900 border border-slate-800 prose prose-invert max-w-none"><h1>{kind==='terms'?'Điều khoản sử dụng':'Chính sách bảo mật'}</h1>{kind==='terms' ? <><p>Chào mừng bạn đến D Social. Khi sử dụng dịch vụ, bạn đồng ý sử dụng nền tảng đúng pháp luật, tôn trọng người khác và không đăng nội dung xâm hại, lừa đảo, spam hoặc vi phạm quyền của bên thứ ba.</p><h2>Tài khoản</h2><p>Bạn chịu trách nhiệm bảo vệ thông tin đăng nhập và hoạt động phát sinh từ tài khoản của mình. D Social có thể giới hạn hoặc khóa tài khoản vi phạm quy định.</p><h2>Nội dung</h2><p>Bạn giữ quyền đối với nội dung hợp pháp do mình tạo, đồng thời cấp cho D Social quyền kỹ thuật cần thiết để lưu trữ và hiển thị nội dung trong phạm vi vận hành dịch vụ.</p><h2>Thanh toán</h2><p>Các giao dịch nạp tiền/VIP được xử lý qua đối tác thanh toán. Giao dịch thành công được ghi nhận theo webhook xác thực của hệ thống thanh toán.</p><h2>Liên hệ</h2><p>Chủ dịch vụ cần bổ sung tên pháp nhân, địa chỉ, email hỗ trợ và quy định hoàn tiền cụ thể trước khi kinh doanh chính thức.</p></> : <><p>D Social chỉ thu thập dữ liệu cần thiết cho tài khoản, xác thực, nội dung, tương tác, tin nhắn và thanh toán. Dữ liệu được sử dụng để cung cấp, bảo vệ và cải thiện dịch vụ.</p><h2>Dữ liệu</h2><p>Thông tin hồ sơ, bài viết, media, lượt thích, bình luận và tin nhắn được lưu trong hệ thống. Thông tin thanh toán được lưu dưới dạng giao dịch và mã tham chiếu; thông tin nhạy cảm của phương thức thanh toán không được lưu trong frontend.</p><h2>Bảo mật</h2><p>Hệ thống áp dụng Supabase Auth, Row Level Security, quyền Storage và xử lý khóa bí mật phía server. Không chia sẻ service role key hoặc khóa thanh toán trong trình duyệt.</p><h2>Quyền của người dùng</h2><p>Người dùng có thể yêu cầu cập nhật hoặc xóa dữ liệu tài khoản theo quy trình hỗ trợ. Chủ dịch vụ cần bổ sung đầu mối tiếp nhận yêu cầu và thời hạn xử lý trước khi phát hành chính thức.</p></>}</article></main>
}

function Composer({ userId, onPublished }: { userId: string; onPublished:()=>void }) {
  const [text,setText]=useState(''); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  const pick = (f: File|undefined) => { if(!f)return; const limit=f.type.startsWith('video/')?MAX_VIDEO:MAX_IMAGE; if(!['image/','video/'].some(x=>f.type.startsWith(x))||f.size>limit)return setError(`File không hợp lệ hoặc quá ${f.type.startsWith('video/')?'30MB':'8MB'}.`); setError('');setFile(f) }
  const publish=async()=>{ if(!supabase)return; const mod=moderateText(text); if(!mod.allowed)return setError(mod.reason); if(!text.trim()&&!file)return setError('Hãy nhập nội dung hoặc chọn media.'); setBusy(true);setError(''); try { let media_url=null,media_type=null; if(file){const ext=file.name.split('.').pop()?.toLowerCase()||'bin';const path=`${userId}/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from('social-media').upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;media_url=supabase.storage.from('social-media').getPublicUrl(path).data.publicUrl;media_type=file.type.startsWith('video/')?'video':'image'} const {error}=await supabase.from('posts').insert({author_id:userId,content:text.trim()||null,media_url,media_type});if(error)throw error;setText('');setFile(null);onPublished()} catch(e:any){setError(e.message||'Không thể đăng bài')}finally{setBusy(false)} }
  return <section className="p-4 rounded-2xl bg-slate-900 border border-slate-800"><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder="Bạn đang nghĩ gì?" className="w-full bg-transparent resize-none outline-none min-h-24"/>{file&&<div className="flex items-center justify-between p-2 rounded-lg bg-slate-800 text-sm">{file.name}<button onClick={()=>setFile(null)}><X size={16}/></button></div>}{error&&<p className="text-red-400 text-sm mt-2">{error}</p>}<div className="flex items-center justify-between mt-3"><label className="flex gap-3 text-slate-400 cursor-pointer"><ImageIcon size={20}/><Video size={20}/><input hidden type="file" accept="image/*,video/*" onChange={e=>pick(e.target.files?.[0])}/></label><button disabled={busy} onClick={publish} className="px-5 py-2 rounded-xl bg-indigo-500 disabled:opacity-40">{busy?'Đang đăng...':'Đăng'}</button></div></section>
}

function PostCard({ post, userId, onChanged }: { post:Post; userId:string; onChanged:()=>void }) {
  const [liked,setLiked]=useState(Boolean(post.likes?.some(x=>x.user_id===userId))); const [comments,setComments]=useState<Comment[]>([]); const [show,setShow]=useState(false); const [comment,setComment]=useState(''); const [count,setCount]=useState(post.likes?.length||0)
  useEffect(()=>{if(!supabase||!show)return;loadComments();const ch=supabase.channel(`comments-${post.id}`).on('postgres_changes',{event:'*',schema:'public',table:'comments',filter:`post_id=eq.${post.id}`},loadComments).subscribe();return()=>{supabase.removeChannel(ch)}},[show,post.id])
  const loadComments=async()=>{if(!supabase)return;const {data}=await supabase.from('comments').select('id,post_id,author_id,content,created_at,profiles(id,username,full_name,avatar_url)').eq('post_id',post.id).order('created_at',{ascending:true}).limit(50);if(data)setComments(data as any)}
  const toggleLike=async()=>{if(!supabase)return;if(liked){await supabase.from('likes').delete().eq('post_id',post.id).eq('user_id',userId);setLiked(false);setCount(x=>Math.max(0,x-1))}else{const {error}=await supabase.from('likes').insert({post_id:post.id,user_id:userId});if(!error){setLiked(true);setCount(x=>x+1)}}}
  const addComment=async()=>{if(!supabase)return;const mod=moderateText(comment);if(!mod.allowed)return; if(!comment.trim())return;const {error}=await supabase.from('comments').insert({post_id:post.id,author_id:userId,content:comment.trim()});if(!error)setComment('')}
  return <article className="p-4 rounded-2xl bg-slate-900 border border-slate-800"><div className="flex gap-3"><img src={post.profiles?.avatar_url||''} className="w-10 h-10 rounded-full bg-slate-700 object-cover"/><div><div className="font-bold">{post.profiles?.full_name||post.profiles?.username||'D User'}</div><div className="text-xs text-slate-500">{new Date(post.created_at).toLocaleString('vi-VN')}</div></div></div>{post.content&&<p className="mt-4 whitespace-pre-wrap break-words">{post.content}</p>}{post.media_url&&(post.media_type==='video'?<video src={post.media_url} controls className="mt-4 rounded-xl w-full max-h-[520px]"/>:<img src={post.media_url} loading="lazy" className="mt-4 rounded-xl w-full max-h-[520px] object-cover"/>)}<div className="flex gap-6 mt-4 text-slate-400"><button onClick={toggleLike} className={`flex gap-2 items-center ${liked?'text-pink-400':''}`}><Heart size={19} fill={liked?'currentColor':'none'}/>{count}</button><button onClick={()=>setShow(x=>!x)} className="flex gap-2 items-center"><MessageCircle size={19}/>{show?'Ẩn':'Bình luận'}</button></div>{show&&<div className="mt-4 border-t border-slate-800 pt-3 space-y-3">{comments.map(c=><div key={c.id} className="text-sm"><b>{c.profiles?.full_name||c.profiles?.username||'User'}</b><span className="text-slate-400"> · {c.content}</span></div>)}<div className="flex gap-2"><input value={comment} onChange={e=>setComment(e.target.value)} maxLength={1000} placeholder="Viết bình luận..." className="flex-1 p-2 rounded-lg bg-slate-800 outline-none"/><button onClick={addComment} className="p-2 rounded-lg bg-indigo-500"><Send size={17}/></button></div></div>}</article>
}

function Feed({ userId }: {userId:string}) { const [posts,setPosts]=useState<Post[]>([]);const [page,setPage]=useState(0);const [more,setMore]=useState(true);const [loading,setLoading]=useState(false);const load=async(p=0)=>{if(!supabase)return;setLoading(true);const from=p*PAGE_SIZE,to=from+PAGE_SIZE-1;const {data}=await supabase.from('posts').select('id,author_id,content,media_url,media_type,created_at,profiles(id,username,full_name,avatar_url),likes(user_id)').order('created_at',{ascending:false}).range(from,to);const rows=(data||[]) as any;if(p===0)setPosts(rows);else setPosts(x=>[...x,...rows]);setMore(rows.length===PAGE_SIZE);setLoading(false)};useEffect(()=>{load(0);if(!supabase)return;const ch=supabase.channel('feed-realtime').on('postgres_changes',{event:'*',schema:'public',table:'posts'},()=>load(0)).on('postgres_changes',{event:'*',schema:'public',table:'likes'},()=>load(0)).subscribe();return()=>{supabase.removeChannel(ch)}},[]);return <><Composer userId={userId} onPublished={()=>load(0)}/><div className="space-y-3 mt-4">{posts.map(p=><PostCard key={p.id} post={p} userId={userId} onChanged={()=>load(0)}/>)}{!posts.length&&!loading&&<div className="text-center text-slate-500 py-12">Chưa có bài viết.</div>}{more&&<button onClick={()=>{const n=page+1;setPage(n);load(n)}} disabled={loading} className="w-full py-3 rounded-xl bg-slate-900 border border-slate-800 text-slate-300">{loading?'Đang tải...':'Xem thêm'}</button>}</div></> }

function Chat({ userId }: {userId:string}) { const [users,setUsers]=useState<Profile[]>([]);const [active,setActive]=useState<Profile|null>(null);const [messages,setMessages]=useState<ChatMessage[]>([]);const [text,setText]=useState('');const bottom=useRef<HTMLDivElement>(null);useEffect(()=>{if(!supabase)return;supabase.from('profiles').select('id,username,full_name,avatar_url,is_vip,vip_expires_at').neq('id',userId).limit(50).then(({data})=>setUsers((data||[]) as Profile[]))},[userId]);useEffect(()=>{if(!supabase||!active)return;const load=async()=>{const {data}=await supabase.from('messages').select('*').or(`and(sender_id.eq.${userId},recipient_id.eq.${active.id}),and(sender_id.eq.${active.id},recipient_id.eq.${userId})`).order('created_at',{ascending:true}).limit(200);if(data)setMessages(data)};load();const ch=supabase.channel(`chat-${userId}-${active.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},payload=>{const m=payload.new as ChatMessage;if((m.sender_id===userId&&m.recipient_id===active.id)||(m.sender_id===active.id&&m.recipient_id===userId))setMessages(x=>x.some(y=>y.id===m.id)?x:[...x,m])}).subscribe();return()=>{supabase.removeChannel(ch)}},[active,userId]);useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[messages]);const send=async()=>{if(!supabase||!active||!text.trim())return;const mod=moderateText(text);if(!mod.allowed)return;const {error}=await supabase.from('messages').insert({sender_id:userId,recipient_id:active.id,content:text.trim()});if(!error)setText('')};return <div className="grid md:grid-cols-[180px_1fr] gap-3 min-h-[65vh]"><aside className="rounded-2xl bg-slate-900 border border-slate-800 p-2">{users.map(u=><button key={u.id} onClick={()=>setActive(u)} className={`w-full text-left p-3 rounded-xl ${active?.id===u.id?'bg-slate-800':''}`}>{u.full_name||u.username||'D User'}</button>)}{!users.length&&<p className="p-3 text-sm text-slate-500">Chưa có người dùng khác.</p>}</aside><section className="rounded-2xl bg-slate-900 border border-slate-800 flex flex-col">{!active?<div className="m-auto text-slate-500">Chọn một người để bắt đầu chat.</div>:<><header className="p-4 border-b border-slate-800 font-bold">{active.full_name||active.username}</header><div className="flex-1 p-4 space-y-2 overflow-auto max-h-[55vh]">{messages.map(m=><div key={m.id} className={`flex ${m.sender_id===userId?'justify-end':'justify-start'}`}><div className={`max-w-[80%] px-3 py-2 rounded-2xl ${m.sender_id===userId?'bg-indigo-500':'bg-slate-800'}`}>{m.content}</div></div>)}<div ref={bottom}/></div><div className="p-3 border-t border-slate-800 flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} maxLength={4000} placeholder="Nhắn tin..." className="flex-1 p-3 rounded-xl bg-slate-800 outline-none"/><button onClick={send} className="p-3 rounded-xl bg-indigo-500"><Send size={18}/></button></div></>}</section></div> }

function ProfilePage({ userId }: {userId:string}) { const [p,setP]=useState<Profile|null>(null);const [name,setName]=useState('');const [username,setUsername]=useState('');const [bio,setBio]=useState('');const [saved,setSaved]=useState(false);useEffect(()=>{if(!supabase)return;supabase.from('profiles').select('*').eq('id',userId).single().then(({data})=>{if(data){setP(data);setName(data.full_name||'');setUsername(data.username||'');setBio(data.bio||'')}})},[userId]);const save=async()=>{if(!supabase)return;const {error}=await supabase.from('profiles').update({full_name:name.trim()||null,username:username.trim()||null,bio:bio.trim()||null}).eq('id',userId);if(!error){setSaved(true);setTimeout(()=>setSaved(false),2000)}};return <section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><div className="w-20 h-20 rounded-full bg-slate-700 grid place-items-center"><User/></div><h2 className="text-2xl font-black mt-4">Hồ sơ cá nhân</h2><label className="block mt-4 text-sm text-slate-400">Tên hiển thị<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full p-3 rounded-xl bg-slate-800 outline-none"/></label><label className="block mt-3 text-sm text-slate-400">Username<input value={username} onChange={e=>setUsername(e.target.value.replace(/[^a-zA-Z0-9_]/g,''))} maxLength={30} className="mt-1 w-full p-3 rounded-xl bg-slate-800 outline-none"/></label><label className="block mt-3 text-sm text-slate-400">Giới thiệu<textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={300} className="mt-1 w-full p-3 rounded-xl bg-slate-800 outline-none"/></label><button onClick={save} className="mt-4 px-5 py-3 rounded-xl bg-indigo-500 font-bold">{saved?'Đã lưu ✓':'Lưu hồ sơ'}</button>{p?.is_vip&&<p className="mt-4 text-amber-400">D VIP đến {p.vip_expires_at?new Date(p.vip_expires_at).toLocaleDateString('vi-VN'):'—'}</p>}</section> }

function App() { const [session,setSession]=useState<any>(null);const [tab,setTab]=useState<'feed'|'chat'|'profile'|'wallet'>('feed');const [legal,setLegal]=useState<'terms'|'privacy'|null>(null);useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub.subscription.unsubscribe()},[]);if(legal)return <Legal kind={legal} onBack={()=>setLegal(null)}/>;if(!session&&supabase)return <Auth onLegal={setLegal}/>;if(!session)return <div className="p-8 text-center">D Social</div>;const logout=async()=>{await supabase?.auth.signOut()};return <div className="min-h-screen bg-slate-950 text-white"><header className="sticky top-0 z-20 bg-slate-950/90 backdrop-blur border-b border-slate-800"><div className="max-w-3xl mx-auto px-4 h-16 flex items-center justify-between"><div className="font-black text-2xl">D</div><div className="text-sm text-slate-400">D Social Network</div><button onClick={logout} className="p-2 text-slate-400"><LogOut size={19}/></button></div></header><main className="max-w-3xl mx-auto px-3 py-4 pb-24">{tab==='feed'&&<Feed userId={session.user.id}/>} {tab==='chat'&&<Chat userId={session.user.id}/>} {tab==='profile'&&<ProfilePage userId={session.user.id}/>} {tab==='wallet'&&<section className="p-6 rounded-2xl bg-slate-900 border border-slate-800"><h2 className="text-2xl font-black">Ví & D VIP</h2><p className="text-slate-400 mt-2">Thanh toán payOS được xử lý an toàn ở backend. Giao diện mua VIP sẽ gọi endpoint `/api/payos/create-payment` khi cấu hình khóa môi trường.</p></section>}<div className="flex justify-between mt-6 text-xs text-slate-600"><button onClick={()=>setLegal('terms')}>Điều khoản</button><button onClick={()=>setLegal('privacy')}>Bảo mật</button></div></main><nav className="fixed bottom-0 left-0 right-0 bg-slate-950/95 border-t border-slate-800"><div className="max-w-3xl mx-auto flex justify-around py-3"><button onClick={()=>setTab('feed')}><Home size={20}/><span className="text-xs">Feed</span></button><button onClick={()=>setTab('chat')}><MessageSquare size={20}/><span className="text-xs">Chat</span></button><button onClick={()=>setTab('wallet')}><Wallet size={20}/><span className="text-xs">Ví</span></button><button onClick={()=>setTab('profile')}><User size={20}/><span className="text-xs">Tôi</span></button></div></nav></div> }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
