import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Heart, MessageCircle, Send, User, LogOut, Image as ImageIcon, Video, ShieldCheck } from 'lucide-react'
import { supabase } from './lib/supabase'
import './index.css'

type Post = { id: string; content: string | null; media_url: string | null; media_type: string | null; created_at: string; author?: { username: string | null; full_name: string | null; avatar_url: string | null } }

const demoPosts: Post[] = [
  { id: 'demo-1', content: 'Chào mừng bạn đến với D Social — nơi kết nối đơn giản, nhanh và realtime.', media_url: null, media_type: null, created_at: new Date().toISOString(), author: { username: 'd_social', full_name: 'D Social', avatar_url: null } },
]

function Auth({ onDone }: { onDone: () => void }) {
  const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [sent, setSent] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  if (!supabase) return <div className="max-w-md mx-auto mt-16 p-6 rounded-3xl bg-slate-900 border border-slate-800"><h1 className="text-3xl font-black">D Social</h1><p className="mt-3 text-slate-400">Đã dựng giao diện. Cần cấu hình VITE_SUPABASE_URL và VITE_SUPABASE_PUBLISHABLE_KEY để bật đăng nhập thật.</p></div>
  const google = async () => { const { error } = await supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: window.location.origin } }); if (error) setError(error.message) }
  const emailLogin = async () => { setError(''); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) { const sign = await supabase.auth.signUp({ email, password }); if (sign.error) setError(sign.error.message); else onDone() } else onDone() }
  const sendOtp = async () => { const { error } = await supabase.auth.signInWithOtp({ phone }); if (error) setError(error.message); else setSent(true) }
  const verifyOtp = async () => { const { error } = await supabase.auth.verifyOtp({ phone, token: otp, type: 'sms' }); if (error) setError(error.message); else onDone() }
  return <div className="min-h-screen flex items-center justify-center p-4"><div className="w-full max-w-md p-6 rounded-3xl bg-slate-900 border border-slate-800 shadow-2xl"><div className="w-14 h-14 rounded-2xl bg-white text-slate-950 grid place-items-center text-3xl font-black">D</div><h1 className="text-3xl font-black mt-5">D Social</h1><p className="text-slate-400 mt-1">Mạng xã hội tối giản, realtime.</p><button onClick={google} className="w-full mt-6 py-3 rounded-xl bg-white text-slate-950 font-bold">Tiếp tục với Google</button><div className="my-5 border-t border-slate-800"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="w-full p-3 mb-2 rounded-xl bg-slate-800 outline-none"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu" type="password" className="w-full p-3 rounded-xl bg-slate-800 outline-none"/><button onClick={emailLogin} className="w-full mt-3 py-3 rounded-xl bg-indigo-500 font-bold">Đăng nhập / đăng ký</button><div className="my-5 border-t border-slate-800"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Số điện thoại +84..." className="w-full p-3 rounded-xl bg-slate-800 outline-none"/>{!sent ? <button onClick={sendOtp} className="w-full mt-2 py-3 rounded-xl bg-slate-700 font-bold">Gửi OTP</button> : <><input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="Mã OTP" className="w-full p-3 mt-2 rounded-xl bg-slate-800 outline-none"/><button onClick={verifyOtp} className="w-full mt-2 py-3 rounded-xl bg-emerald-500 font-bold">Xác nhận OTP</button></>}{error && <p className="text-red-400 mt-3 text-sm">{error}</p>}</div></div>
}

function App() {
  const [session, setSession] = useState<any>(null); const [posts, setPosts] = useState<Post[]>(demoPosts); const [text, setText] = useState(''); const [loading, setLoading] = useState(false); const [tab, setTab] = useState<'feed'|'profile'>('feed');
  useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({data}) => setSession(data.session)); const {data: sub} = supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return () => sub.subscription.unsubscribe() }, [])
  useEffect(() => { if (!supabase || !session) return; loadPosts(); const channel = supabase.channel('posts-feed').on('postgres_changes',{event:'*',schema:'public',table:'posts'},()=>loadPosts()).subscribe(); return () => { supabase.removeChannel(channel) } }, [session])
  const loadPosts = async () => { if (!supabase) return; const {data} = await supabase.from('posts').select('id,content,media_url,media_type,created_at,profiles(username,full_name,avatar_url)').order('created_at',{ascending:false}).range(0,19); if (data) setPosts(data as any) }
  const publish = async () => { if (!supabase || !session || !text.trim()) return; setLoading(true); const {error} = await supabase.from('posts').insert({author_id:session.user.id,content:text.trim()}); setLoading(false); if (!error) setText('') }
  const logout = async () => { await supabase?.auth.signOut(); setSession(null) }
  if (!session && supabase) return <Auth onDone={()=>{}} />
  return <div className="min-h-screen bg-slate-950 text-white"><header className="sticky top-0 z-20 bg-slate-950/90 backdrop-blur border-b border-slate-800"><div className="max-w-2xl mx-auto px-4 h-16 flex items-center justify-between"><div className="font-black text-2xl">D</div><div className="text-sm text-slate-400">D Social Network</div>{session && <button onClick={logout} className="p-2 text-slate-400"><LogOut size={19}/></button>}</div></header><main className="max-w-2xl mx-auto px-3 pb-24">{tab==='feed' ? <><section className="mt-4 p-4 rounded-2xl bg-slate-900 border border-slate-800"><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder="Bạn đang nghĩ gì?" className="w-full bg-transparent resize-none outline-none min-h-24"/><div className="flex items-center justify-between mt-3"><div className="flex gap-2 text-slate-400"><ImageIcon size={20}/><Video size={20}/><ShieldCheck size={20}/></div><button disabled={!text.trim()||loading||!session} onClick={publish} className="px-5 py-2 rounded-xl bg-indigo-500 disabled:opacity-40 flex gap-2 items-center">{loading?'Đang đăng...':<>Đăng <Send size={16}/></>}</button></div></section><div className="space-y-3 mt-4">{posts.map(p=><article key={p.id} className="p-4 rounded-2xl bg-slate-900 border border-slate-800"><div className="flex gap-3"><div className="w-10 h-10 rounded-full bg-slate-700 grid place-items-center"><User size={18}/></div><div><div className="font-bold">{p.author?.full_name || p.author?.username || 'D User'}</div><div className="text-xs text-slate-500">{new Date(p.created_at).toLocaleString('vi-VN')}</div></div></div>{p.content && <p className="mt-4 whitespace-pre-wrap break-words">{p.content}</p>}{p.media_url && (p.media_type?.startsWith('video') ? <video src={p.media_url} controls className="mt-4 rounded-xl w-full"/> : <img src={p.media_url} className="mt-4 rounded-xl w-full"/>)}<div className="flex gap-6 mt-4 text-slate-400"><button className="flex gap-2 items-center"><Heart size={19}/>Thích</button><button className="flex gap-2 items-center"><MessageCircle size={19}/>Bình luận</button></div></article>)}</div></> : <section className="mt-4 p-6 rounded-2xl bg-slate-900 border border-slate-800"><h2 className="text-2xl font-bold">Hồ sơ</h2><p className="text-slate-400 mt-2">{session?.user?.email || 'Người dùng D'}</p></section>}</main><nav className="fixed bottom-0 left-0 right-0 bg-slate-950/95 border-t border-slate-800"><div className="max-w-2xl mx-auto flex justify-around py-3"><button onClick={()=>setTab('feed')} className="font-bold">Bảng tin</button><button onClick={()=>setTab('profile')} className="font-bold">Hồ sơ</button></div></nav></div>
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
